### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by miriamhaenle** [miriamhaenle/capstone-project#41]
### Value statement
As a triathlete
I want to be able to reset my password in case I forgot it
so that I can still continue using the app.

### Description
![Forgot password](https://user-images.githubusercontent.com/60315975/87949648-96b44580-caa6-11ea-9931-88cafedd6ef2.png)

### Acceptance criteria
- [x] Clicking on forgot password link will open new view
- [x] User can enter her email address
- [x] If email address exists an email is sent to the user to reset it
- [x] User can go back to login view by tapping "Go back"

### Tasks
- [x] Create feature branch
- [x] Update component in Storybook
- [x] Connect with firebase auth
- [ ] Add component tests
- [ ] Write integration tests w/ Cypress
