### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by miriamhaenle** [miriamhaenle/capstone-project#42]
### Value statement
As a user 
I want to be able to edit my profile data
so that I can keep my personal data up to date.

### Description
![User Profile](https://user-images.githubusercontent.com/60315975/87950279-61f4be00-caa7-11ea-9cd6-6405fbb72083.png)

### Acceptance criteria

- [x] Clicking on the user icon will lead to user profile
- [x] User can edit her personal data: name, email, password
- [x] User needs to click on edit button to start editing
- [x] By clicking on save the new data will be updated  in the view

### Tasks

- [x] Create feature branch
- [ ] Update component in Storybook
- [ ] Add component tests
- [x] Update firestore connection (db)
- [ ] Write integration tests w/ Cypress
